{% set version = "0.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geometries
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geometries_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geometries/geometries_{{ version }}.tar.gz
  sha256: 642fd7b5b98be3197616b38c5eb7e59f93859ad327800ab8af65b8d5b18a9e77

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp

test:
  commands:
    - $R -e "library('geometries')"           # [not win]
    - "\"%R%\" -e \"library('geometries')\""  # [win]

about:
  home: https://dcooley.github.io/geometries/
  license: MIT
  summary: Geometry shapes in 'R' are typically represented by matrices (points, lines), with more complex shapes being lists of matrices (polygons). 'Geometries' will convert various 'R' objects into these shapes. Conversion functions are available at both the 'R' level, and through 'Rcpp'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: geometries
# Type: Package
# Title: Convert Between R Objects and Geometric Structures
# Date: 2020-08-02
# Version: 0.1.0
# Authors@R: c( person("David", "Cooley", ,"david.cooley.au@gmail.com", role = c("aut", "cre")) )
# Description: Geometry shapes in 'R' are typically represented by matrices (points, lines), with more complex shapes being lists of matrices (polygons). 'Geometries' will convert various 'R' objects into these shapes. Conversion functions are available at both the 'R' level, and through 'Rcpp'.
# License: MIT + file LICENSE
# URL: https://dcooley.github.io/geometries/
# BugReports: https://github.com/dcooley/geometries/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.0
# SystemRequirements: C++11
# LinkingTo: Rcpp
# Imports: Rcpp
# Suggests: knitr, rmarkdown, tinytest, covr
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2020-08-09 21:32:31 UTC; dave
# Author: David Cooley [aut, cre]
# Maintainer: David Cooley <david.cooley.au@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-08-14 14:20:03 UTC
